services:
  db:
    image: postgres:15
    container_name: readocs_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/database:/docker-entrypoint-initdb.d
  api:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/sh", "./entrypoint.sh"]
volumes:
  postgres_data: